### PR TITLE
provide default file path for sonarqube

### PR DESCRIPTION
**Pull request by fnxpt**

### CODE REVIEW

**Comment by fnxpt** [comment]
Fixes #17

**Comment by LeoLogeart** [comment]
The readme may need to be updated as well

**Comment by fnxpt** [comment]
> The readme may need to be updated as well

done

**Comment by ajinabraham** [comment]
I am back after vacation, will take a look at this soon.

**Comment by fnxpt** [comment]
@ajinabraham any update on this PR and the others?

**Comment by LeoLogeart** [comment]
Any update on this PR?

**Comment by ajinabraham** [comment]
Thanks for commenting. I am just getting back to my projects. 

For this one, I do not like the idea of having a new command line argument for specifying a filename for sonarqube. It just doesn't feel right. 

Is sonarqube happy with a non existing path like the parent directory of the scan instead of file? 
If a filename is required then another option is to set something like the parent directory  + `.non_existent_file`
Or if it requires a file like object, then do an `ls` on the parent directory to scan and pass the first file in the list.

**Comment by LeoLogeart** [comment]
The file path must exist within the Sonar-analyzed sources. Otherwise, the issue is ignored by Sonar.
The problem with `ls` is that it may select a file that is excluded by the Sonar analysis.
That is why the chosen solution so far is to pass a path as a parameter.

**Comment by fnxpt** [comment]
My initial idea was to map it against the project file but like @LeoLogeart mentioned this can be excluded, so the best option is to allow the users to specify the file path.

**Comment by ajinabraham** [comment]
> The file path must exist within the Sonar-analyzed sources.

Here the analysis is done by a third party tool, i.e. mobsfscan,  so how come sonar determine what's analyzed? Or does sonar has a say on the file extension? (PS: I haven't tested or used this integration before. This feature was a community contribution)

mobsfscan looks at files with extensions `.kt, .java, .swift, .m`. With a recursive `ls`, you should be able to get a file with one of these extension. Can we use that?

**Comment by fnxpt** [comment]
These vulnerabilities are generic and not specific to a file, I think it's better to be able to specify a file instead of getting a file with ls, like @LeoLogeart mentioned the project can be configured to skip some paths or files and with ls we also have the risk of mapping it with a file that it's going to be ignored

**Comment by fnxpt** [comment]
@ajinabraham Happy New year.... can you have a look at this?

**Comment by ajinabraham** [comment]
It looks like sonar expects a finding to be associated with a file and mobsfscan produces certain findings (missing best practices) that are not associated with any files. The right place to fix this is at sonar's end, having the ability to import such best practices.  Alternatively you can disable these best practices rules in mobsfscan.

Having to hack it up with a sonar file path CLI option just to support sonar doesn't feel right. In future, on the same line we may get similar 3rd party specific requirements and I do not prefer to include such hacks. We can revisit this if it's more of a concern from the community in the long run.

**Comment by fnxpt** [comment]
@ajinabraham what if we don't set the default file but we do all the rest, so keeping the primary location but with file path as null, this way we can manipulate the results outside mobsfscan

**Comment by ajinabraham** [comment]
Sure, As long as the details are internally handled, I am good.

**Pull request closed without merging**
