### PR TITLE
Sonarqube primary location information

### PR DESCRIPTION
**Pull request by fnxpt**
As discussed on #20, instead of returning an empty primary location we return a primary location with an empty file path, this way its possible to manipulate this information outside mobsfscan, like using bash to replace the file path with your own file path

### CODE REVIEW

**Review by ajinabraham — APPROVED** [review]
LGTM

**Comment by fnxpt** [comment]
@ajinabraham can you do a new release with these changes?

**Comment by ajinabraham** [comment]
This should go in soon with few other changes that I am working on.

**Comment by emartinson** [comment]
Hi @ajinabraham, do you have any ETA for this changes to be merged?

**Comment by DPutkov** [comment]
ERROR: Error during SonarScanner execution
]java.lang.IllegalStateException: Failed to parse report 'sonar.json': missing mandatory field 'filePath' in the primary location of the issue.

Hi there!
There is still an error parsing a report.

**Pull request merged**
