### PR TITLE
Fix SARIF and duplication issues

### PR DESCRIPTION
**Pull request by ls-valentinas-bakaitis**
This PR fixes two issues:
https://github.com/MobSF/mobsfscan/issues/90
and
https://github.com/MobSF/mobsfscan/issues/15 - while this has been closed as completed - I don't see any changes related to it and the behaviour still seems to be in the main branch. This PR fixes the issue.

### CODE REVIEW

**Comment by ajinabraham** [comment]
can you send the changes against libsast as well?

**Comment by ls-valentinas-bakaitis** [comment]
@ajinabraham I have raised a pull request for libsast here: https://github.com/ajinabraham/libsast/pull/46/files.

**Comment by ls-valentinas-bakaitis** [comment]
@ajinabraham this pull request has some changes that shouldn't be merged to main (because I ended up switching to our own fork of libsast), but you can probably cherry pick `291da9ffe83fcbb78267f2cb739d2ccb80ba7540` and `3d3fca46da11a05f71d57425f38d18e360c263d3` to get the needed changes. Then once Libsast PR is merged, you can update libsast.

**Comment by ajinabraham** [comment]
Thanks, I am working on this, will take a look and include the changes appropriately

**Comment by ls-valentinas-bakaitis** [comment]
@ajinabraham thank you, that is much appreciated! If you have any questions or need any help with these changes - feel free to reply here.

**Comment by ajinabraham** [comment]
Can you update the PR to use latest libsast?

**Comment by valentinas** [comment]
Yep, will do shortly :)

**Comment by ls-valentinas-bakaitis** [comment]
@ajinabraham does this look ok?

**Pull request merged**
